import { Finding } from "../rules/types";

export interface AnalysisResult {
  docId: string;
  pagesCount: number;
  overallScore: number;
  summary: string[];
  risks: Finding[];
}

/**
 * Generates JSON report.
 */
export function generateJsonReport(result: AnalysisResult): string {
  return JSON.stringify(result, null, 2);
}

/**
 * Generates Markdown report.
 */
export function generateMarkdownReport(result: AnalysisResult): string {
  let md = `# Contract Risk Analysis Report\n\n`;
  md += `**Document ID:** ${result.docId}\n`;
  md += `**Pages:** ${result.pagesCount}\n`;
  md += `**Overall Risk Score:** ${result.overallScore.toFixed(1)}/100\n\n`;

  md += `## Executive Summary\n\n`;
  for (const bullet of result.summary) {
    md += `- ${bullet}\n`;
  }
  md += `\n`;

  md += `## Detailed Findings\n\n`;
  md += `Total Risks Found: ${result.risks.length}\n\n`;

  // Group by category
  const byCategory = new Map<string, Finding[]>();
  for (const risk of result.risks) {
    if (!byCategory.has(risk.category)) {
      byCategory.set(risk.category, []);
    }
    byCategory.get(risk.category)!.push(risk);
  }

  for (const [category, risks] of Array.from(byCategory.entries()).sort()) {
    md += `### ${category}\n\n`;
    for (const risk of risks.sort((a, b) => b.score - a.score)) {
      md += `**Risk ID:** ${risk.ruleId}\n`;
      md += `**Severity:** ${risk.severity.toUpperCase()}\n`;
      md += `**Score:** ${risk.score}/100\n`;
      md += `**Page:** ${risk.page}\n`;
      md += `**Quote:** "${risk.quote}"\n`;
      md += `**Explanation:** ${risk.explanation}\n`;
      md += `**Suggestion:** ${risk.suggestion}\n\n`;
    }
  }

  md += `---\n\n`;
  md += `*This report is generated by an automated tool and is not legal advice.*\n`;

  return md;
}
